name: Unit Test

on: [ push ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: Unit Test
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Build docker images
      run: docker-compose build
    - name: Run docker images
      run: docker-compose up -d
    - run: yarn install
    - name: Unit test
      run: yarn test
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
